spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: medicine-service
          uri: lb://medicine-service
          predicates:
            - Path=/api/medicines/**
          filters:
            - StripPrefix=2
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=2
        - id: alert-service
          uri: lb://alert-service
          predicates:
            - Path=/api/alert/**
          filters:
            - StripPrefix=2

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/